title: CCTC Digital Media
logo: /assets/img/logo.png
description: Video and animation classes for Caddo Parish high school students.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
